#!/usr/bin/env bash
# Requirements:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Holberton School
# As an answer file, write a Bash script that configures a new Ubuntu
# machine to respect above requirements
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" >/var/www/html/index.nginx-debian.html
service nginx restart
