#!/usr/bin/env bash
# intall nginx web server and configure to port 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
