#!/usr/bin/env bash
# Install nginx web server and configure to port 80
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "46i rewrite ^/redirect_me  permanent;" /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo sed -i '18i add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-enabled/default
sudo service nginx restart
