#!/usr/bin/env bash
# This is 
# Requirements:
# You cannot use pgrep
# The third line of your script must be # shellcheck disable=SC2009
# (for more info about ignoring shellcheck error here)
ps -aux | grep bash

