#!/usr/bin/env bash
# This is Bash script that displays lines containing the bash word
# shellcheck disable=SC2009
# Requirements:
# You cannot use pgrep
# The third line of your script must be # shellcheck disable=SC2009
# (for more info about ignoring shellcheck error here)
ps -aux | grep bash

