#!/usr/bin/env bash
# Thi is a Bash script that displays Holberton School 10 times
# You must use the for loop (while and until are forbidden)
count=0

while [ $count -lt 10 ]; do
	echo "Holberton School"
	if [ $count -eq 8 ]; then
		echo "Hi"
	fi
	count=$((count+1))
done

