#!/usr/bin/env bash
# This is a Bash script that loops from 1 to 10 and:
# Displays bad luck for the 4th loop iteration
# Displays good luck for the 8th loop iteration
# Displays Holberton School for the other iterations
# Requirements:
# You must use the while loop (for and until are forbidden)
# You must use the if, elif and else statements
count=1

while [ $count -lt 11 ]; do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	count=$((count+1))
done
