#!/usr/bin/env bash
# This is a Bash script that displays the time for 12 hours and 59 minutes:
# Display hours from 0 to 12
# Display minutes from 1 to 59
# Requirements:
# You must use the while loop (for and until are forbidden)
hours=0

while [ $hours -le 12 ]; do
	echo "Hour: $hours"
	minutes=1
	while [ $minutes -le 59 ]; do
		echo "$minutes"
		minutes=$((minutes+1))
	done
	hours=$((hours+1))
done

