#!/usr/bin/env bash
# This is a Bash script that configures an Ubuntu server with the below requirements
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker, so make sure to read this

sudo sed -i s/127.0.0.1/127.0.0.2/ /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
