#!/usr/bin/env bash
# Requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
# ABash script that configures the container to fit the above requirements

sudo pkill apache2
sudo chmod 660 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
