#!/usr/bin/env bash
# Create nginx how user and group
sudo pkill apache2
sudo chmod 660 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
